### ISSUE TITLE
Dependency missing in package.json like node-uuid

### ISSUE THREAD

**Issue by chitreshd** [ebayGive/library-summer-reading#1]
When I downloaded the latest version of the code I am getting following error:
[Wed, 25 Feb 2015 06:50:08 GMT] INFO Creating 1 worker process.

module.js:340
    throw err;
          ^
Error: Cannot find module 'node-uuid'
    at Function.Module._resolveFilename (module.js:338:15)
    at Function.Module._load (module.js:280:25)
    at Module.require (module.js:364:17)
    at require (module.js:380:17)
    at Object.<anonymous> (/Users/cdeshpande/workspace/library-summer-reading/app/models/account.js:1:74)
    at Module._compile (module.js:456:26)
    at Object.Module._extensions..js (module.js:474:10)
    at Module.load (module.js:356:32)
    at Function.Module._load (module.js:312:12)
    at Module.require (module.js:364:17)
[Wed, 25 Feb 2015 06:50:08 GMT] ERROR Worker 1339 died.
LM-SJC-00877502:library-summer-reading cdeshpande$

**Comment by chitreshd** [comment]
When i added node-uuid, it fails with following error:
/Users/cdeshpande/workspace/library-summer-reading/node_modules/mongodb/lib/mongodb/mongo_client.js:378
          throw err
                ^
Error: failed to connect to [localhost:27017]
    at null.<anonymous> (/Users/cdeshpande/workspace/library-summer-reading/node_modules/mongodb/lib/mongodb/connection/server.js:553:74)
    at emit (events.js:106:17)
    at null.<anonymous> (/Users/cdeshpande/workspace/library-summer-reading/node_modules/mongodb/lib/mongodb/connection/connection_pool.js:140:15)
    at emit (events.js:98:17)
    at Socket.<anonymous> (/Users/cdeshpande/workspace/library-summer-reading/node_modules/mongodb/lib/mongodb/connection/connection.js:512:10)
    at Socket.emit (events.js:95:17)
    at net.js:440:14
    at process._tickDomainCallback (node.js:463:13)
